version: '3.8'

services:
  backend:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    command: uvicorn back.back:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  frontend:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    # Запускаем Gradio через main.py
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "7860:7860"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

volumes:
  postgres_data: