version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "7861:7861"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_PORT=7861
      - PYTHONPATH=/app
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped 

  backend:
    build: .
    command: python front_and_back/back.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      - app-network
    restart: unless-stopped 

networks:
  app-network:
    driver: bridge