version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "7861:7861"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_PORT=7861
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: .
    command: python back.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge