version: '3.8'

# Docker Compose конфигурация для Trivy Security Scanner
# Использование: docker-compose -f trivy/docker-compose.trivy.yml run --rm trivy-scan
# Документация: ./README.md

services:
  # Сервис Trivy для сканирования безопасности
  trivy-scan:
    # Закрепленная версия: 0.63.0 (выпущена 30.05.2025)
    # Для обеспечения воспроизводимости сборок используется конкретная версия
    # Проверить актуальность: https://github.com/aquasecurity/trivy/releases
    image: aquasec/trivy:0.63.0
    container_name: trivy_scanner
    
    # Монтируем необходимые директории
    volumes:
      # Docker socket для доступа к локальным образам
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # Кэш Trivy для ускорения повторных сканирований
      # Используется переменная окружения TRIVY_CACHE_DIR
      - trivy-cache:${TRIVY_CACHE_DIR:-/tmp/trivy-cache}
      
      # Конфигурационные файлы
      - ./trivy-config.yaml:/config/trivy-config.yaml:ro
      
      # Файл с исключениями CVE (монтируется в рабочую директорию)
      - ../.trivyignore:/work/.trivyignore:ro
      
      # Директории для отчётов и логов
      - ./reports:/reports
      - ./logs:/logs
    
    # Переменные окружения
    environment:
      # Конфигурация Trivy
      - TRIVY_CONFIG=/config/trivy-config.yaml
      
      # Кэш директория (можно переопределить через .env или docker-compose)
      - TRIVY_CACHE_DIR=${TRIVY_CACHE_DIR:-/tmp/trivy-cache}
      
      # Основные настройки
      - TRIVY_DEBUG=false
      - TRIVY_TIMEOUT=10m
      
      # Настройки отчётов
      - TRIVY_FORMAT=table
      - TRIVY_SEVERITY=CRITICAL,HIGH,MEDIUM
      
      # Дополнительные опции
      - TRIVY_NO_PROGRESS=false
      - TRIVY_QUIET=false
    
    # Команда по умолчанию (можно переопределить при запуске)
    command: --help
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Политики безопасности
    security_opt:
      - no-new-privileges:true
    
    # Только чтение файловой системы (кроме /tmp и кэша)
    read_only: true
    tmpfs:
      - /tmp

volumes:
  # Кэш для базы данных уязвимостей Trivy
  trivy-cache:
    driver: local

networks:
  default:
    name: trivy_network

