# =============================================================================
# Конфигурация Trivy Security Scanner
# =============================================================================
# Документация: https://aquasecurity.github.io/trivy/latest/docs/
# Дата создания: 2025-10-08
# =============================================================================

# -----------------------------------------------------------------------------
# Основные настройки сканирования
# -----------------------------------------------------------------------------
scan:
  # Типы сканирования (vuln, misconfig, secret, license)
  scanners:
    - vuln        # Сканирование уязвимостей в пакетах
    - misconfig   # Поиск неправильных конфигураций
    - secret      # Обнаружение утечек секретов (пароли, токены, ключи)
  
  # Уровни важности для отображения
  # Опции: UNKNOWN, LOW, MEDIUM, HIGH, CRITICAL
  severity:
    - CRITICAL
    - HIGH
    - MEDIUM
  
  # Пропускать незакреплённые уязвимости (без доступных патчей)
  ignore-unfixed: false
  
  # Таймаут сканирования
  timeout: 10m

# -----------------------------------------------------------------------------
# Настройки базы данных уязвимостей
# -----------------------------------------------------------------------------
db:
  # Пропустить обновление базы данных (для offline режима)
  skip-db-update: false
  
  # Репозиторий базы данных
  # repository: ghcr.io/aquasecurity/trivy-db
  
  # Пропустить обновление Java базы данных
  skip-java-db-update: false

# -----------------------------------------------------------------------------
# Настройки кэширования
# -----------------------------------------------------------------------------
cache:
  # Директория кэша
  # Использует переменную окружения TRIVY_CACHE_DIR с fallback на ./cache
  # Для переопределения: export TRIVY_CACHE_DIR=/custom/path
  dir: ${TRIVY_CACHE_DIR:-./.trivy-cache}
  
  # Очистить кэш перед сканированием
  clear: false

# -----------------------------------------------------------------------------
# Настройки вывода и отчётов
# -----------------------------------------------------------------------------
output:
  # Формат вывода: table, json, sarif, template, cyclonedx, spdx, github
  format: table
  
  # Файл для сохранения результатов
  # file: /reports/scan-report.json
  
  # Шаблон для форматирования (если format=template)
  # template: "@contrib/html.tpl"

# -----------------------------------------------------------------------------
# Настройки vulnerability сканирования
# -----------------------------------------------------------------------------
vulnerability:
  # Тип уязвимостей для сканирования
  type:
    - os      # Уязвимости в пакетах ОС
    - library # Уязвимости в библиотеках языков программирования
  
  # VEX (Vulnerability Exploitability eXchange) источники
  # vex: []

# -----------------------------------------------------------------------------
# Настройки misconfiguration сканирования
# -----------------------------------------------------------------------------
misconfiguration:
  # Включить проверку конфигураций
  enabled: true
  
  # Типы файлов для сканирования
  # ansible, cloudformation, dockerfile, helm, kubernetes, terraform, etc.
  include-non-failures: false
  
  # Трассировка политик Rego
  trace: false

# -----------------------------------------------------------------------------
# Настройки secret сканирования
# -----------------------------------------------------------------------------
secret:
  # Включить поиск секретов
  enabled: true
  
  # Конфигурационный файл для секретов
  # config: secret-config.yaml

# -----------------------------------------------------------------------------
# Настройки license сканирования
# -----------------------------------------------------------------------------
license:
  # Включить сканирование лицензий
  enabled: false
  
  # Уровень строгости: CRITICAL, HIGH, MEDIUM, LOW
  # severity:
  #   - HIGH
  #   - CRITICAL
  
  # Полное сканирование лицензий (медленнее, но точнее)
  full: false

# -----------------------------------------------------------------------------
# Политики выхода (Production-Safe Configuration)
# -----------------------------------------------------------------------------
exit:
  # Код выхода при обнаружении уязвимостей
  # 0 = не прерывать выполнение (только для разработки)
  # 1 = прерывать при обнаружении уязвимостей указанного уровня
  code: 1
  
  # Прерывать выполнение при обнаружении критических и высоких уязвимостей
  # Опции: CRITICAL, HIGH, MEDIUM, LOW
  on-severity:
    - CRITICAL
    - HIGH

# -----------------------------------------------------------------------------
# Дополнительные настройки
# -----------------------------------------------------------------------------
# Игнорировать файл с исключениями
# Относительный путь от директории сканирования
ignorefile: .trivyignore

# Отключить отправку анонимной статистики
no-progress: false

# Тихий режим (только ошибки)
quiet: false

# Режим отладки
debug: false

# -----------------------------------------------------------------------------
# Фильтры и исключения
# -----------------------------------------------------------------------------
# Пропустить директории при сканировании
# skip-dirs:
#   - node_modules
#   - vendor

# Пропустить файлы при сканировании
# skip-files:
#   - "*.md"
#   - "*.txt"

# -----------------------------------------------------------------------------
# Примечания:
# -----------------------------------------------------------------------------
# 1. Production-safe: exit.code установлен в 1 для CRITICAL/HIGH уязвимостей
# 2. TRIVY_CACHE_DIR: переопределяйте через переменную окружения
# 3. Файл .trivyignore должен находиться в директории проекта
# 4. Для development временно установите exit.code: 0 если нужно
# 5. Полную документацию смотрите: https://aquasecurity.github.io/trivy/
# =============================================================================

