version: '3.7'

services:
  bot:
    build: .
    container_name: sales_bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./user_data:/app/user_data
      - ./steps:/app/steps
      - ./db:/app/db
      - ./prompts:/app/prompts
      - ./.env:/app/.env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GPT_MODEL=${GPT_MODEL}
      - BASE_URL=${BASE_URL}
      - MAX_REQUESTS_PER_DAY=${MAX_REQUESTS_PER_DAY}
      - MAX_REQUESTS_PER_USER=${MAX_REQUESTS_PER_USER}
    mem_limit: 512M
    cpus: 0.5
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:exec,mode=777
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python bot.py' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bot_net

networks:
  bot_net:
    driver: bridge